name: Simple project

on:
  pull_request:
    branches:
      - main

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v3
      - name: Intall dependecies
        run: npm ci

  unit-tests:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 20

      - name: Intall Dependecies
        run: npm ci

      - name: Check Jest installation
        run: ls node_modules/.bin

      - name: Run jest testes
        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v3

      - name: Intall Dependecies
        run: npm ci

      - name: Build project
        run: npm run build

  e2e-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 20

      - name: Intall Dependecies
        run: npm ci

      - name: Start the application
        run: npm run start &
        env:
          NODE_ENV: test

      - name: Wait for the app to be ready
        run: npx wait-on http://localhost:8080

      - name: Run Cypress tests
        run: npx cypress open
