name: Simple project

on:
  pull_request:
    branches:
      - main

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci

      - name: Archive node_modules artifacts
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: node_modules/

  unit-tests:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependecies
        uses: actions/download-artifact@v4
        with:
          name: node_modules

      - name: Run jest testes
        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependecies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: .next/

  e2e-tests:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependecies
        run: npm ci

      - name: Install production build
        run: npm run build

      - name: Start the application
        run: npm run start &
        env:
          NODE_ENV: test

      - name: Wait for the app to be ready
        run: npx wait-on http://localhost:3000

      - name: Cypress run
        uses: cypress-io/github-action@v6
